device_list: [33, 26] # List of device IDs
experiment_time_sec: 10 # Experiment time in seconds
offered_load_percent: 80 # Aggregate network offered load
packet_size_bytes: 16
mac_protocol: "aloha" # MAC protocol used by the devices
packet_arrival_model: "poisson" # Packet generation model used by the devices.
# PHY layer parameters
transmit_SF: "SF8" # Spreading factor
receive_SF: "SF8"
transmit_BW: "BW125" # Bandwidth: "BW125", "BW250", "BW500
receive_BW: "BW125"
transmit_CR: "CR_4_8" # Code rate
receive_CR: "CR_4_8"
