device_list: [28, 29]
experiment_time_sec: 30
transmit_interval_msec: 100
packet_size_bytes: 16
mac_protocol: "aloha"
packet_arrival_model: "poisson"
transmit_SF: "SF8"
receive_SF: "SF8"
transmit_BW: "BW125"
receive_BW: "BW125"
transmit_CR: "CR_4_8"
receive_CR: "CR_4_8"
